defaults: &defaults
  working_directory: /tmp/image_build
  docker:
    - image: mumblepins/circleci-dev


version: 2
jobs:
  build-beta:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            set -e
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            ./build beta deploy
  build-experimental:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            set -e
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            ./build experimental deploy
  build-canary:
    <<: *defaults
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker Image
          command: |
            set -e
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            ./build canary deploy

workflows:
  version: 2
  build-all:
    jobs:
      - build-beta
      - build-canary
      - build-experimental
